WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 930
MENU_WINDOW_WIDTH = 200
MENU_WINDOW_HEIGHT = 400
GAME_WINDOW_WIDTH = 200
GAME_WINDOW_HEIGHT = 200
MENU_WINDOW_X_PADDING = 50
SNAKE_SIZE = 20

PIXEL_WIDTH = GAME_WINDOW_WIDTH // SNAKE_SIZE
PIXEL_HEIGHT = GAME_WINDOW_HEIGHT // SNAKE_SIZE

MENU_START_X = GAME_WINDOW_WIDTH + MENU_WINDOW_X_PADDING


VALID_TURNS = {
    "left" : ["up", "down"],
    "right" : ["up", "down"],
    "up" : ["left", "right"],
    "down" : ["left", "right"]
}
